#include "solvers.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <numeric>
#include <random>
#include <sstream>
namespace tsp { namespace {using Clock=std::chrono::steady_clock;double Sec(Clock::time_point s){return std::chrono::duration<double>(Clock::now()-s).count();}}
Result SolveAntColony(const Matrix&d,std::uint64_t seed,int ants,int iterations,double alpha,double beta,double evaporation){auto start=Clock::now();int n=d.size();std::mt19937_64 rng(seed);std::vector<std::vector<double>>pher(n,std::vector<double>(n,1.0/n)),eta(n,std::vector<double>(n));for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j)eta[i][j]=1.0/d[i][j];auto best=TwoOpt(NearestNeighbor(0,d),d);auto best_len=TourLength(best,d);std::vector<ProgressPoint>progress;
for(int iter=0;iter<iterations;++iter){std::vector<std::vector<int>>tours;std::vector<std::int64_t>lengths;for(int ant=0;ant<ants;++ant){std::vector<int>route{ant%n};std::vector<bool>seen(n);seen[route[0]]=true;while((int)route.size()<n){int current=route.back();std::vector<double>w(n);double total=0;for(int node=0;node<n;++node)if(!seen[node])total+=w[node]=std::pow(pher[current][node],alpha)*std::pow(eta[current][node],beta);std::uniform_real_distribution<double>choose(0,total);double draw=choose(rng);int next=-1;for(int node=0;node<n;++node)if(!seen[node]&&(draw-=w[node])<=0){next=node;break;}if(next<0)for(int node=n-1;node>=0;--node)if(!seen[node]){next=node;break;}route.push_back(next);seen[next]=true;}auto len=TourLength(route,d);if(len<best_len){best_len=len;best=route;}tours.push_back(std::move(route));lengths.push_back(len);}for(auto&row:pher)for(double&v:row)v*=1-evaporation;std::vector<int>order(ants);std::iota(order.begin(),order.end(),0);std::sort(order.begin(),order.end(),[&](int a,int b){return lengths[a]<lengths[b];});for(int rank=0;rank<std::max(3,ants/5);++rank){auto&route=tours[order[rank]];double add=1.0/lengths[order[rank]];for(int i=0;i<n;++i){int a=route[i],b=route[(i+1)%n];pher[a][b]+=add;pher[b][a]+=add;}}double elite=2.0/best_len;for(int i=0;i<n;++i){int a=best[i],b=best[(i+1)%n];pher[a][b]+=elite;pher[b][a]+=elite;}progress.push_back({iter,best_len,Sec(start)});}
best=TwoOpt(best,d);best_len=TourLength(best,d);double runtime=Sec(start);progress.push_back({iterations,best_len,runtime});std::ostringstream p;p<<"{\"seed\": "<<seed<<", \"ants\": "<<ants<<", \"iterations\": "<<iterations<<", \"alpha\": "<<alpha<<", \"beta\": "<<beta<<", \"evaporation\": "<<evaporation<<"}";return{"ACO",CanonicalTour(best),best_len,runtime,std::move(progress),p.str()};}
}
